### ISSUE TITLE
Assemble errores

### ISSUE THREAD

**Issue by tjiangHIT** [EichlerLab/pacbio_variant_caller#51]
When I use the `smrtsv.py assemble`, I got some errors like this:

_**[INFO] 2016-09-30T18:35:30 [loadPulses] started.
ERROR, could not read FileLog of the cmp file.
Error in job convert_assembly_alignments_to_hdf5 while creating output file alignment.cmp.h5.
RuleException:
CalledProcessError in line 88 of /home/tjiang/Tools/pacbio_variant_caller/rules/local_assembly.mhap_celera_single_assembly.rules:**_

My command is " ~/Tools/pacbio_variant_caller/bin/smrtsv.py assemble ~/Reference/hg19.fa ../../reads-bax-h5.fofn ../alignments.fofn ../candidates.bed local_assembly_alignments.bam ".
How can I fix this error?

**Comment by huddlej** [comment]
There are many reasons assemblies can fail and result in an invalid "pulse" file. A couple questions about your environment:

  * Did you try running the [example yeast data set in the tutorial](https://github.com/EichlerLab/pacbio_variant_caller#tutorial-for-variant-calling)? This is the best way to confirm the pipeline itself is working with a control data set.
  * Do all of your assemblies fail with the error you describe or is it only a subset of all assemblies that fail?

**Comment by tjiangHIT** [comment]
I had run the example data and got the same error also.
What's more, all of my data couldn't be assembled.

**Comment by huddlej** [comment]
This issue should be fixed by a [recent commit to the EichlerLab BLASR fork](https://github.com/EichlerLab/blasr/commit/c9bced1fedfb026b4992e2b49e4ffa0f107819ea). Sorry it took so long to fix, but it turned out to be an architecture-specific bug that I could never recreate on my old cluster. Fortunately, the bug appeared on a different cluster where I could troubleshoot it.
