### ISSUE TITLE
Failed to run on the example yeast data set

### ISSUE THREAD

**Issue by haghshenas** [EichlerLab/pacbio_variant_caller#55]
Hi there,
I followed the steps in your tutorial for running smrt-sv on the sample yeast dataset.
Running `smrtsv.py align reference/sacCer3.fasta reads.fofn` failed with the following output:

```
[Fri Dec 23 23:35:28 2016] Provided cores: 1
[Fri Dec 23 23:35:28 2016] Rules claiming more threads will be scaled down.
[Fri Dec 23 23:35:28 2016] Job counts:
	count	jobs
	1	align_batch
	1	align_reads
	1	assign_batches
	3
[Fri Dec 23 23:35:28 2016] localrule assign_batches:
    input: reads.fofn
    output: alignments_reads/0.fofn
    wildcards: batch_id=0
[Fri Dec 23 23:35:28 2016] 
[Fri Dec 23 23:35:30 2016] 1 of 3 steps (33%) done
[Fri Dec 23 23:35:30 2016] rule align_batch:
    input: reference/sacCer3.fasta.ctab, alignments_reads/0.fofn, reference/sacCer3.fasta, reference/sacCer3.fasta.sa
    output: alignments/0.bam
    wildcards: batch_id=0
[Fri Dec 23 23:35:30 2016] 
Processed 1735 (10008359 bp)
Processed 3287 (20006044 bp)
Processed 4965 (30013217 bp)
Processed 6610 (40002152 bp)
Processed 7840 (50011505 bp)
Processed 9009 (60003977 bp)
Processed 10175 (70016604 bp)
Processed 11330 (80000094 bp)
Processed 12506 (90003416 bp)
Processed 13687 (100000137 bp)
Processed 14868 (110001935 bp)
Processed 16047 (120010031 bp)
Processed 17217 (130000940 bp)
Processed 18380 (140000296 bp)
Processed 19550 (150014764 bp)
Processed 20726 (160004416 bp)
Processed 21864 (170009659 bp)
Processed 23014 (180016525 bp)
Processed 24168 (190003794 bp)
Processed 25334 (200000767 bp)
Processed 26440 (210006943 bp)
Processed 27541 (220005301 bp)
Processed 28622 (230002264 bp)
Processed 29746 (240014418 bp)
Processed 30907 (250007138 bp)
Processed 32108 (260008981 bp)
[E::hts_open_format] fail to open file '0.0000.bam'
[bam_sort_core] failed to create temporary file "0.0000.bam": File exists
[Sat Dec 24 00:08:00 2016] Error in job align_batch while creating output file alignments/0.bam.
[Sat Dec 24 00:08:00 2016] RuleException:
CalledProcessError in line 63 of /vol/cluster-data/ehaghshe/soft/smrtsv/rules/alignment.rules:
Command 'export REFERENCE_PATH=`readlink -f reference/sacCer3.fasta`; export REFERENCE_SUFFIX_PATH=`readlink -f reference/sacCer3.fasta.sa`; export REFERENCE_CTAB_PATH=`readlink -f reference/sacCer3.fasta.ctab`; mkdir -p /var/tmp/0; cd /var/tmp/0; set -o pipefail; set -e; blasr /prj/longread-sv/arabTh-Nd1/sv/test_smrtsv2/alignments_reads/0.fofn $REFERENCE_PATH -unaligned /dev/null -out /dev/stdout -sam -sa $REFERENCE_SUFFIX_PATH -ctab $REFERENCE_CTAB_PATH -nproc 1 -clipping subread -bestn 2 -maxAnchorsPerPosition 100 -advanceExactMatches 10 -affineAlign -affineOpen 100 -affineExtend 0 -insertion 5 -deletion 5 -extend -maxExtendDropoff 50 | samtools view -F 0x4 -hS - | samtools sort -@ 1 -m 4G -O bam -T 0 -o 0.bam -; samtools index 0.bam; rsync --bwlimit=30000 --remove-source-files 0.bam* /prj/longread-sv/arabTh-Nd1/sv/test_smrtsv2/`dirname alignments/0.bam`/; rm -rf /var/tmp/0; ' returned non-zero exit status 1
  File "/vol/cluster-data/ehaghshe/soft/smrtsv/rules/alignment.rules", line 63, in __rule_align_batch
  File "/vol/cluster-data/ehaghshe/soft/smrtsv/dist/miniconda/envs/python3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
[Sat Dec 24 00:08:00 2016] Will exit after finishing currently running jobs.
[Sat Dec 24 00:08:00 2016] Exiting because a job execution failed. Look above for error message
```
Could you let me know how to fix this?

**Comment by FredMasc** [comment]
Hi!
I have the same problem. Is there a fix?
Thanks

**Comment by FredMasc** [comment]
...
...
Processed 10589 (250007949 bp)
Processed 11016 (260015332 bp)
[E::hts_open_format] fail to open file '0.0000.bam'
[bam_sort_core] failed to create temporary file "0.0000.bam": No such file or directory
[Fri Jul 21 21:21:22 2017] Error in job align_batch while creating output file alignments/0.bam.
[Fri Jul 21 21:21:22 2017] RuleException:
CalledProcessError in line 63 of /scratch/beegfs/monthly/fmasclau/PROG2/SMRT-SV-v3/rules/alignment.rules:
Command 'export REFERENCE_PATH=`readlink -f reference/Rhizophagus-A5-genomeC.fa`; export REFERENCE_SUFFIX_PATH=`readlink -f reference/Rhizophagus-A5-genomeC.fa.sa`; export REFERENCE_CTAB_PATH=`readlink -f reference/Rhizophagus-A5-genomeC.fa.ctab`; mkdir -p /var/tmp/0; cd /var/tmp/0; set -o pipefail; set -e; blasr /scratch/local/monthly/fmasclau/PcTEST/alignments_reads/0.fofn $REFERENCE_PATH -unaligned /dev/null -out /dev/stdout -sam -sa $REFERENCE_SUFFIX_PATH -ctab $REFERENCE_CTAB_PATH -nproc 25 -clipping subread -bestn 2 -maxAnchorsPerPosition 100 -advanceExactMatches 10 -affineAlign -affineOpen 100 -affineExtend 0 -insertion 5 -deletion 5 -extend -maxExtendDropoff 50 | samtools view -F 0x4 -hS - | samtools sort -@ 1 -m 4G -O bam -T 0 -o 0.bam -; samtools index 0.bam; rsync --bwlimit=30000 --remove-source-files 0.bam* /scratch/local/monthly/fmasclau/PcTEST/`dirname alignments/0.bam`/; rm -rf /var/tmp/0; ' returned non-zero exit status 1.
  File "/scratch/beegfs/monthly/fmasclau/PROG2/SMRT-SV-v3/rules/alignment.rules", line 63, in __rule_align_batch
  File "/scratch/beegfs/monthly/fmasclau/PROG2/SMRT-SV-v3/dist/miniconda/envs/python3/lib/python3.6/concurrent/futures/thread.py", line 55, in run
[Fri Jul 21 21:21:22 2017] Will exit after finishing currently running jobs.
[Fri Jul 21 21:21:22 2017] Exiting because a job execution failed. Look above for error message

**Comment by paudano** [comment]
Closing. This project has been replaced with SMRT-SV v2 (https://github.com/EichlerLab/smrtsv2)
